[package]
name = "tid"
version = "0.1.0"
authors = ["MarimeGui <lepro.guillaume@gmail.com>"]

[dependencies]
magic_number = { git = "https://github.com/MarimeGui/magic_number_rust.git" }
ez_io = { git = "https://github.com/MarimeGui/ez_io.git" }
clap = "2.31.2"
rgb = "0.8.11"